services:
  bmw-bridge:
    image: ghcr.io/oemich/bmw-mqtt-bridge:latest
    environment:
      - XDG_STATE_HOME=/app/state          # Parent; Bridge nutzt /app/state/bmw-mqtt-bridge
      - LOCAL_HOST=host.docker.internal    # MQTT läuft i.d.R. auf dem Host
      - LOCAL_PORT=1883
      - LOCAL_PREFIX=bmw/
    volumes:
      - ${HOME}/.local/state:/app/state    # Host-State ↔ Container-State (bind mount)
    restart: unless-stopped
