site_name: BMW CarData → MQTT Bridge
site_url: https://dj0abr.github.io/bmw-mqtt-bridge
repo_url: https://github.com/dj0abr/bmw-mqtt-bridge
repo_name: dj0abr/bmw-mqtt-bridge

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - content.code.copy
    - search.suggest
  language: en

nav:
  - Overview: index.md
  - Installation:
      - Classic Installation: install.md
      - Docker Setup: docker.md
      - Get Your BMW IDs: ids.md
  - Usage:
      - Environment Variables (.env): env.md
      - MQTT Topics: mqtt.md
      - MQTT Retain: retain.md
      - System Service (systemd): service.md
  - Security: security.md
  - License: license.md
  - Credits: credits.md

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dj0abr/bmw-mqtt-bridge

plugins:
  - search
